# -*- coding: utf-8 -*-
"""Time Series Prophet

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DyzjZkmSmr3Ko9Ed6QLwmi4Alsg7Kmel
"""



!pip install prophet

from prophet import Prophet
import pandas as pd

dir(Prophet)





df1=pd.read_csv("/content/oil.csv")
df1

df2=pd.read_csv("/content/transactions.csv")
df2

df1=df1.dropna()
df1

df1[["dcoilwtico"]].describe()

import matplotlib.pyplot as plt
df1.plot()

df1.columns=["ds","y"]
df1

fb=Prophet()
fb.fit(df1)

fd=fb.make_future_dataframe(periods=365)

fd

pred=fb.predict(fd)
pred

fb.plot(pred)

fb.plot_components(pred)

from prophet.diagnostics import cross_validation
df_cv = cross_validation(fb, initial='730 days', period='180 days', horizon = '365 days')
df_cv.head()

from prophet.diagnostics import performance_metrics
dfp = performance_metrics(df_cv)
dfp

from prophet.plot import plot_cross_validation_metric
fig = plot_cross_validation_metric(df_cv, metric='rmse')

from prophet.plot import plot_cross_validation_metric
fig = plot_cross_validation_metric(df_cv, metric='mse')

